import {useState} from 'react';
import {ShieldCheck,KeyRound,Mail,Smartphone} from 'lucide-react';
import {api,stamp,type Row} from './api';
import {useData,ErrorBox,Loading} from './ui';

export function AccountSecurity({onUpdated}:{onUpdated?:()=>void}){
  const [version,setVersion]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[otp,setOtp]=useState<Row>({}),[mfa,setMfa]=useState<Row|null>(null),[codes,setCodes]=useState<string[]>([]);
  const state=useData<Row>('/auth/security',version),sessions=useData<Row[]>('/auth/sessions',version);
  const user=state.data;
  function changed(){setVersion(v=>v+1);window.dispatchEvent(new Event('society-security-changed'));onUpdated?.();}
  async function run(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!user)return <><ErrorBox message={state.error}/><Loading/></>;
  return <section className="security-area"><div className="section-heading"><div><p className="eyebrow">ACCOUNT SECURITY</p><h2><ShieldCheck size={22}/> Verify and protect your account</h2><p className="muted">{user.setup_required?.length?'Complete the required steps to open your society workspace.':'Your verification methods, sign-in protection and active devices.'}</p></div></div><ErrorBox message={error||state.error}/>{message&&<p className="success-note" role="status">{message}</p>}
  <div className="security-grid"><section className="panel settings-panel"><h3><Mail size={18}/> Contact & notifications</h3><p className="small muted">Email: {user.email_verified?'Verified':'Verification required'} · Phone: {user.phone_verified?'Verified':'Not verified'}</p>
  <form key={String(user.email)+String(user.phone)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/auth/contact','PUT',{email:f.get('email')||null,phone:f.get('phone')||null,password:f.get('password'),code:f.get('code')||'',email_notifications:f.get('email_notifications')==='on',sms_notifications:f.get('sms_notifications')==='on'});setMessage('Contact saved. Verify any changed destination.');setOtp({});changed();});}}>
  <label className="field"><span>Email address</span><input name="email" type="email" defaultValue={user.email||''}/></label><label className="field"><span>Mobile number (with country code)</span><input name="phone" type="tel" placeholder="+919876543210" defaultValue={user.phone||''} pattern="\+[1-9][0-9]{7,14}"/></label><label className="check-field"><input name="email_notifications" type="checkbox" defaultChecked={user.email_notifications}/> Email society updates</label><label className="check-field"><input name="sms_notifications" type="checkbox" defaultChecked={user.sms_notifications}/> SMS society updates</label>
  <label className="field"><span>Current password</span><input type="password" name="password" required autoComplete="current-password"/></label>{user.mfa_enabled&&<label className="field"><span>Authenticator / recovery code</span><input name="code" required autoComplete="one-time-code"/></label>}<button className="button" disabled={busy}>Save contacts</button></form>
  {(['email','sms'] as const).map(channel=><div className="verify-contact" key={channel}><h4>{channel==='email'?<Mail size={16}/>:<Smartphone size={16}/>} {channel==='email'?'Email verification':'Phone verification'}</h4>{!user[channel==='email'?'email_ready':'sms_ready']&&<p className="small muted">Administrator must configure {channel==='email'?'SMTP':'SMS provider'} first.</p>}<button className="button" disabled={busy||!user[channel==='email'?'email_ready':'sms_ready']} onClick={()=>run(async()=>{const result=await api(`/auth/verify/${channel}/send`,'POST');setOtp(v=>({...v,[channel]:result.challenge}));setMessage(result.message);})}>Send verification code</button>{otp[channel]&&<form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api(`/auth/verify/${channel}/confirm`,'POST',{challenge:otp[channel],code:f.get('code')});setOtp(v=>({...v,[channel]:null}));setMessage('Contact verified');changed();});}}><input name="code" inputMode="numeric" placeholder="6-digit code" required autoComplete="one-time-code"/><button className="button primary" disabled={busy}>Verify</button></form>}</div>)}
  </section><section className="panel settings-panel"><h3><KeyRound size={18}/> Authenticator app</h3><p className="muted">{user.mfa_enabled?'Two-factor sign-in is enabled.':'Use an authenticator app to scan the QR code.'} {user.mfa_required?'Required for your role.':'Optional for your role.'}</p>
  {!mfa&&!codes.length&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const payload={password:f.get('password'),code:f.get('code')||''};if(user.mfa_enabled){await api('/auth/mfa/disable','POST',payload);setMessage('Authenticator removed. Required accounts must enroll again before continuing.');changed();}else setMfa(await api('/auth/mfa/setup','POST',payload));});}}><label className="field"><span>Current password</span><input name="password" type="password" required/></label>{user.mfa_enabled&&<label className="field"><span>Authenticator / recovery code</span><input name="code" required/></label>}<button className="button" disabled={busy}>{user.mfa_enabled?'Remove authenticator':'Set up authenticator'}</button>{user.mfa_enabled&&<p className="small muted">{user.recovery_codes_remaining} unused recovery codes. Each authenticator code works once; wait for a new code between sensitive actions.</p>}</form>}
  {mfa&&<><img className="mfa-qr" src={mfa.qr} alt="Scan with your authenticator app"/><p className="small">Manual setup key: <code className="break-anywhere">{mfa.secret}</code></p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const result=await api('/auth/mfa/confirm','POST',{challenge:mfa.challenge,code:f.get('code')});setCodes(result.recovery_codes);setMfa(null);setVersion(v=>v+1);});}}><label className="field"><span>Code from your authenticator</span><input name="code" required inputMode="numeric" autoComplete="one-time-code"/></label><button className="button primary" disabled={busy}>Enable two-factor sign-in</button></form></>}
  {!!codes.length&&<div className="recovery-codes"><strong>Save these recovery codes now</strong><p>Each code works once. Keep them in a password manager; they will not be shown again.</p><pre>{codes.join('\n')}</pre><button className="button primary" onClick={()=>{setCodes([]);changed();}}>I have saved my recovery codes</button></div>}
  <hr/><h3>Change password</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/auth/password','POST',{current_password:f.get('current_password'),new_password:f.get('new_password'),code:f.get('code')||''});setMessage('Password updated. Other sessions have been signed out.');changed();});}}><label className="field"><span>Current password</span><input name="current_password" type="password" required/></label><label className="field"><span>New password (12+ characters)</span><input name="new_password" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label>{user.mfa_enabled&&<label className="field"><span>Authenticator / recovery code</span><input name="code" required/></label>}<button className="button" disabled={busy}>Update password</button></form>
  </section></div><section className="panel settings-panel"><h3>Active sessions</h3><ErrorBox message={sessions.error}/>{sessions.data?.map(item=><div className="session-line" key={item.id}><div><strong>{item.current?'This device':item.device||'Browser session'}</strong><small>{item.ip} · Last active {stamp(item.last_seen)}</small></div><button className="button" onClick={()=>run(async()=>{await api('/auth/sessions/'+item.id,'DELETE');if(item.current)window.dispatchEvent(new Event('society-session-expired'));else setVersion(v=>v+1);})}>Sign out</button></div>)}</section></section>;
}
