import {useEffect,useState} from 'react';
import {Building2,ShieldCheck,Eye,EyeOff,ArrowRight,Menu,X,Moon,Sun,LogOut,ChevronDown,CheckCircle2,RefreshCw} from 'lucide-react';
import {api,setCsrf,type Row,type User} from './api';
import {ErrorBox,Loading} from './ui';
import {modules} from './modules';
import {Records} from './Records';
import {Dashboard} from './Dashboard';
import {Gate} from './Gate';
import {Settings} from './Settings';
import {Login} from './Login';
import {AccountSecurity} from './AccountSecurity';
import {Integrations} from './Integrations';

export default function App(){
  const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[page,setPage]=useState(location.hash.slice(1)||'overview'),[open,setOpen]=useState(false),[version,setVersion]=useState(0),[options,setOptions]=useState<Row>({}),[society,setSociety]=useState<Row>({}),[error,setError]=useState(''),[toast,setToast]=useState(''),[dark,setDark]=useState(()=>localStorage.getItem('society-theme')==='dark');
  function signedIn(value:User){setCsrf(value.csrf);setUser(value);setVersion(v=>v+1);}
  useEffect(()=>{api<User>('/auth/me').then(signedIn).catch(()=>{}).finally(()=>setLoading(false));const onHash=()=>{setPage(location.hash.slice(1)||'overview');setOpen(false);};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('society-theme',dark?'dark':'light');},[dark]);
  useEffect(()=>{function expired(){setUser(null);setCsrf('');setOptions({});setSociety({});setError('');}window.addEventListener('society-session-expired',expired);return()=>window.removeEventListener('society-session-expired',expired);},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);},[toast]);
  useEffect(()=>{if(!user||user.setup_required?.length)return;let active=true;Promise.all([api<Row>('/options'),api<Row>('/society')]).then(([o,s])=>{if(active){setOptions(o);setSociety(s);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[user,version]);
  useEffect(()=>{const handler=()=>api<User>('/auth/me').then(u=>{setCsrf(u.csrf);setUser(u);}).catch(()=>{});window.addEventListener('society-security-changed',handler);return()=>window.removeEventListener('society-security-changed',handler);},[]);
  async function logout(){try{await api('/auth/logout','POST');setUser(null);setCsrf('');setOptions({});setSociety({});location.hash='overview';}catch(e){setError((e as Error).message);}}
  if(loading)return <div className="boot"><Building2 size={35}/><Loading/></div>;
  if(!user||location.hash.startsWith('#reset='))return <Login onLogin={signedIn}/>;
  if(user.setup_required?.length)return <main className="setup-screen"><header className="setup-header"><span className="brand-mark"><Building2/></span><div><strong>Nayantra Society</strong><p>Welcome, {user.name}. Complete your account setup.</p></div><button className="button" onClick={logout}>Sign out</button></header><AccountSecurity onUpdated={()=>api<User>('/auth/me').then(signedIn)}/></main>;
  const visible=modules.filter(m=>m.roles.includes(user.role)),definition=visible.find(m=>m.id===page)||visible[0],groups=Array.from(new Set(visible.map(m=>m.group)));
  const shared={user,options,version,refresh:()=>setVersion(v=>v+1),notify:setToast};
  return <div className="app-shell">{open&&<button className="sidebar-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={'sidebar '+(open?'open':'')}><a className="brand" href="#overview"><span className="brand-mark"><Building2 size={25}/></span><span>NAYANTRA<small>SOCIETY</small></span></a><button className="mobile-close icon-button" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button><div className="society-switch"><span className="society-avatar"><Building2 size={19}/></span><span><strong>{society.name||'Your society'}</strong><small>Residential community</small></span></div><nav aria-label="Main navigation">{groups.map(group=><div className="nav-group" key={group}><p>{group}</p>{visible.filter(m=>m.group===group).map(m=><a key={m.id} href={'#'+m.id} className={m.id===definition.id?'active':''} aria-current={m.id===definition.id?'page':undefined}><m.icon size={18}/><span>{m.title}</span>{m.id===definition.id&&<span className="nav-active-dot"/>}</a>)}</div>)}</nav><div className="sidebar-bottom"><span className="shield-tile"><ShieldCheck size={18}/></span><div><strong>Your community workspace</strong><small>Connected. Considered. Secure.</small></div></div></aside>
  <div className="workspace"><header className="topbar"><div className="topbar-context"><button className="icon-button mobile-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={21}/></button><span className="breadcrumb">Society workspace <span>/</span> <strong>{definition.title}</strong></span></div><div className="topbar-actions"><button className="icon-button" aria-label="Refresh records" onClick={shared.refresh}><RefreshCw size={17}/></button><button className="icon-button" aria-label={dark?'Use light theme':'Use dark theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><span className="topbar-divider"/><a href="#settings" className="profile"><span className="avatar">{user.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span><strong>{user.name}</strong><small>{user.role}</small></span></a><button className="icon-button" aria-label="Sign out" onClick={logout}><LogOut size={18}/></button></div></header><main className="main-content"><ErrorBox message={error}/>{definition.id==='overview'?<Dashboard user={user} version={version} society={society}/>:definition.id==='gate'?<Gate {...shared}/>:definition.id==='integrations'?<Integrations {...shared}/>:definition.id==='settings'?<Settings {...shared} society={society}/>:<Records key={definition.id} definition={definition} {...shared}/>}</main><footer className="app-footer"><span>Nayantra Society</span><span>One place for a better community.</span></footer></div>{toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={15}/></button></div>}</div>;
}
