import {ArrowUpRight,Building2,Users,UserRoundCheck,Wallet,ClipboardList,ShieldCheck,DoorOpen,CalendarDays,Clock3,Megaphone,Package,ShieldAlert} from 'lucide-react';
import {money,stamp,type Row} from './api';
import {Empty,ErrorBox,Loading,Status,useData} from './ui';
import type {Shared} from './Records';
import {modules,security,finance} from './modules';

export function Dashboard({user,version,society}:{user:Shared['user'];version:number;society:Row}){
  const {data,error,loading}=useData<Row>('/dashboard',version);
  if(loading)return <Loading/>;
  if(!data)return <ErrorBox message={error}/>;
  const s=data.summary,isSecurity=security.includes(user.role),isFinance=finance.includes(user.role)||user.role==='resident';
  const cards=[
    s.flats!==undefined?{name:user.role==='resident'?'Your home':'Homes in the society',value:s.flats,sub:'Registered flats',icon:Building2,to:'flats',tone:'blue'}:null,
    s.people_inside!==undefined?{name:'Members inside',value:s.people_inside,sub:'Residents and staff on premises',icon:Users,to:user.role==='staff'?'staff':'residents',tone:'teal'}:null,
    s.visitors_inside!==undefined?{name:'Visitors inside',value:s.visitors_inside,sub:s.pending_visitors+' awaiting approval',icon:UserRoundCheck,to:'visitors',tone:'orange'}:null,
    isFinance?{name:'Maintenance outstanding',value:money(s.outstanding_paise),sub:'Across unpaid invoices',icon:Wallet,to:'invoices',tone:'purple'}:{name:'Open service requests',value:s.open_complaints,sub:'Awaiting assignment or resolution',icon:ClipboardList,to:'complaints',tone:'purple'},
  ].filter(Boolean) as Row[];
  const quick=['gate','visitors','complaints','invoices','bookings','deliveries'].map(id=>modules.find(x=>x.id===id)!).filter(x=>x.roles.includes(user.role)).slice(0,4);
  return <><div className="page-title"><div><p className="eyebrow">YOUR COMMUNITY, CONNECTED</p><h1>Welcome, {user.name.split(' ')[0]}<span className="greeting-dot">.</span></h1><p>Here’s what’s happening at {society.name||'your society'}.</p></div><span className="date-pill"><CalendarDays size={16}/>{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</span></div>
    <ErrorBox message={error}/>
    <section className="community-hero"><div className="hero-copy"><span className="hero-tag"><ShieldCheck size={14}/> NAYANTRA SOCIETY</span><h2>A better everyday.<br/>For your whole community.</h2><p>Safer arrivals, smoother operations and a place where every home stays connected.</p><a href={isSecurity?'#gate':'#notices'} className="button hero-button">{isSecurity?'Open gate console':'View community updates'}<ArrowUpRight size={17}/></a></div><div className="hero-art" aria-hidden="true"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="skyline"><div className="tower tower-back"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="tower tower-main"><div className="roof"/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><span className="tower-door"/></div><div className="tower tower-side"><i/><i/><i/><i/><i/><i/></div></div><div className="tree tree-one"/><div className="tree tree-two"/><div className="hero-ground"/><div className="floating-label"><span className="pulse-dot"/> One community. One place.</div></div></section>
    <div className={'stats-grid stats-'+cards.length}>{cards.map(c=><a href={'#'+c.to} className="stat-card" key={c.name}><div className="stat-top"><span className={'stat-icon '+c.tone}><c.icon size={20}/></span><ArrowUpRight size={17}/></div><p>{c.name}</p><strong>{c.value}</strong><small>{c.sub}</small></a>)}</div>
    <div className="dashboard-columns"><div className="dashboard-main"><section className="panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>The everyday, made easier.</p></div></div><div className="quick-grid">{quick.map(q=><a key={q.id} href={'#'+q.id}><span><q.icon size={22}/></span><strong>{q.title}</strong><ArrowUpRight size={16}/></a>)}</div></section>
    <section className="panel"><div className="panel-heading"><div><h2>{user.role==='accountant'?'Accounts at a glance':'Recent gate activity'}</h2><p>{user.role==='accountant'?'Verified payments and current dues.':'The latest recorded arrivals and departures.'}</p></div>{user.role!=='accountant'&&<a className="text-link" href="#movements">View log <ArrowUpRight size={15}/></a>}</div>{user.role==='accountant'?<div className="finance-summary"><div><span>Payments recorded</span><strong>{money(s.collected_paise)}</strong></div><div><span>Outstanding dues</span><strong>{money(s.outstanding_paise)}</strong></div><a className="button" href="#invoices">Open maintenance ledger</a></div>:data.recent_movements.length?<div className="activity-list">{data.recent_movements.map((r:Row)=><div key={r.id} className="activity-row"><span className={'activity-symbol '+(r.decision==='allowed'?'teal':'red')}><DoorOpen size={19}/></span><div><strong>{r.subject_name}</strong><small>{r.gate_name} · {r.direction==='in'?'Arrival':'Departure'} · {r.subject_kind}</small></div><div className="activity-result"><Status value={r.decision}/><small>{stamp(r.created_at)}</small></div></div>)}</div>:<Empty title="Ready for the first arrival">Gate activity will appear here as entries and exits are recorded.</Empty>}</section></div>
    <aside className="dashboard-aside"><section className="panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>A few things to keep an eye on.</p></div><Clock3 size={18}/></div><div className="attention-list">{s.pending_visitors!==undefined&&<a href="#visitors"><span className="attention-icon orange"><UserRoundCheck size={18}/></span><span>Visitor approvals</span><b>{s.pending_visitors}</b></a>}{s.overdue_visitors>0&&<a href="#visitors"><span className="attention-icon red"><Clock3 size={18}/></span><span>Visitors past pass expiry</span><b>{s.overdue_visitors}</b></a>}<a href="#complaints"><span className="attention-icon purple"><ClipboardList size={18}/></span><span>Open service requests</span><b>{s.open_complaints}</b></a>{s.open_incidents!==undefined&&<a href="#incidents"><span className="attention-icon red"><ShieldAlert size={18}/></span><span>Security incidents</span><b>{s.open_incidents}</b></a>}</div></section>
    <section className="panel notice-panel"><div className="panel-heading"><div><h2>Community board</h2><p>News from your neighbourhood.</p></div><Megaphone size={19}/></div>{data.notices.length?<div className="notice-list">{data.notices.map((n:Row)=><a href="#notices" key={n.id}><div>{n.pinned&&<span className="notice-pin">PINNED</span>}<small>{new Date(n.created_at).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div><h3>{n.title}</h3><p>{n.body}</p></a>)}</div>:<div className="aside-empty"><Megaphone size={24}/><p>No announcements yet.</p></div>}<a href="#notices" className="notice-footer">All announcements <ArrowUpRight size={16}/></a></section>
    <a href="#contacts" className="emergency-card"><ShieldCheck size={25}/><div><strong>Help is always close</strong><p>Society & emergency contacts</p></div><ArrowUpRight size={17}/></a></aside></div><p className="sync-note"><span className="pulse-dot"/>Updated {new Date(data.updated_at).toLocaleTimeString('en-IN')} · Refreshes every 15 seconds</p></>;
}
