import {useState} from 'react';
import {ScanFace} from 'lucide-react';
import {api,type Row,type User} from './api';
import {useData,ErrorBox} from './ui';
export function FaceEnrollment({person,user,version,refresh,notify}:{person:Row;user:User;version:number;refresh:()=>void;notify:(text:string)=>void}){
 const state=useData<Row>(`/people/${person.id}/face`,version),[error,setError]=useState(''),[busy,setBusy]=useState(false),manager=['admin','manager'].includes(user.role);
 async function revoke(){if(!window.confirm('Remove this person’s stored face templates? Their gate pass remains available.'))return;setBusy(true);try{await api(`/people/${person.id}/face`,'DELETE');refresh();notify('Face enrollment revoked');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="detail-section no-print"><h3><ScanFace size={19}/> Automatic face enrollment</h3><ErrorBox message={error||state.error}/><p>{state.data?.enrolled?`Enrolled · ${state.data.samples} views`:'No active face enrollment'}</p><p className="small muted">Use 3–8 sharp photos of this person: front and slight left/right turns. Each photo must show exactly one face. Enrollment and camera matching use the same model.</p>{manager&&<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const payload=new FormData(form);setBusy(true);setError('');api(`/people/${person.id}/face`,'POST',payload).then(()=>{form.reset();refresh();notify('Face enrollment saved');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label className="field"><span>Face photos (3–8 JPEG/PNG files)</span><input name="images" type="file" accept="image/jpeg,image/png" multiple required/></label><label className="check-field"><input type="checkbox" name="consent" value="true" required/> This person has explicitly consented to face enrollment for society gate access.</label><button className="button primary" disabled={busy}>{busy?'Processing photos…':'Save face enrollment'}</button></form>}{state.data?.enrolled&&<button className="button" disabled={busy} onClick={revoke}>Revoke & delete face templates</button>}<p className="small muted">Photos are processed without retention; encrypted face templates remain until revoked. Camera quality and clear face visibility determine recognition. Guard verification remains available.</p></section>;
}
