import {LayoutDashboard,DoorOpen,Building2,Users,UserRoundCheck,BriefcaseBusiness,ClipboardList,Car,Package,Wallet,CalendarDays,Megaphone,ShieldAlert,Wrench,Contact,Settings,Camera,FileClock,MapPin,Receipt,Store,KeyRound,AlarmClock,NotebookPen} from 'lucide-react';
import type {Field} from './ui';
import type {Row} from './api';
export const managers=['admin','manager'],finance=[...managers,'accountant'],security=[...managers,'guard'],all=[...security,'resident','staff','accountant'];
export type Module={id:string;resource?:string;title:string;subtitle:string;icon:any;group:string;roles:string[];writers?:string[];fields?:Field[];columns?:[string,string][];fixed?:Row;export?:boolean;editable?:boolean};
const f=(key:string,label:string,type='text',extra:Partial<Field>={}):Field=>({key,label,type,...extra});
const required={required:true};
const flat=f('flat_id','Flat','select',{lookup:'flats',...required});
const status=f('status','Status','select',{options:['active','suspended','left'],default:'active',...required});
const personFields=[f('name','Full name','text',required),flat,f('phone','Phone','tel'),f('emergency_contact','Emergency contact'),f('category','Relationship','select',{options:['owner','tenant','family','other'],default:'owner',...required}),status];
export const modules:Module[]=[
  {id:'overview',title:'Community overview',subtitle:'A clear view of your society, all in one place.',icon:LayoutDashboard,group:'WORKSPACE',roles:all},
  {id:'gate',title:'Gate console',subtitle:'Verify arrivals, record departures and keep the entrance moving.',icon:DoorOpen,group:'WORKSPACE',roles:security},
  {id:'flats',title:'Towers & flats',subtitle:'Manage every home, its occupancy and maintenance contribution.',icon:Building2,group:'COMMUNITY',roles:all,writers:managers,editable:true,fields:[f('tower','Tower / block','text',required),f('number','Flat number','text',required),f('floor','Floor','number',{default:0,min:-5,max:150}),f('area_sqft','Area (sq ft)','number',{default:0,min:0}),f('max_occupants','Occupancy limit','number',{default:12,min:1,max:50}),f('maintenance_paise','Monthly maintenance (₹)','money'),f('status','Status','select',{options:['active','maintenance','inactive'],default:'active'})],columns:[['label','Home'],['floor','Floor'],['occupants','Residents'],['maintenance_paise','Monthly dues'],['status','Status']]},
  {id:'residents',resource:'people',fixed:{kind:'resident'},title:'Residents & families',subtitle:'Owners, tenants and family members linked to the right home.',icon:Users,group:'COMMUNITY',roles:[...security,'resident'],writers:managers,editable:true,export:true,fields:personFields,columns:[['name','Resident'],['flat_label','Home'],['category','Relationship'],['phone','Contact'],['presence','Presence'],['status','Membership']]},
  {id:'visitors',title:'Visitors & passes',subtitle:'Resident-approved guest visits with a clear entry and exit trail.',icon:UserRoundCheck,group:'COMMUNITY',roles:[...security,'resident'],writers:[...security,'resident'],export:true,fields:[flat,f('name','Visitor name','text',required),f('phone','Visitor phone','tel'),f('purpose','Purpose of visit','text',required),f('category','Visit type','select',{options:['guest','contractor','delivery','cab','other'],default:'guest'}),f('vehicle_plate','Vehicle number'),f('valid_from','Valid from','datetime',required),f('valid_until','Valid until','datetime',required),f('note','Note for the gate','textarea')],columns:[['name','Visitor'],['flat_label','Visiting'],['purpose','Purpose'],['valid_until','Pass valid until'],['status','Approval']]},
  {id:'staff',resource:'people',fixed:{kind:'staff'},title:'Staff & domestic help',subtitle:'Manage your society team, service providers and shift access.',icon:BriefcaseBusiness,group:'COMMUNITY',roles:[...security,'staff','resident'],writers:managers,editable:true,export:true,fields:[f('name','Full name','text',required),f('phone','Phone','tel'),f('category','Staff role','select',{options:['security','maintenance','housekeeping','gardener','domestic_help','driver','other'],default:'maintenance'}),f('company','Employer / agency'),{...flat,required:false,label:'Assigned flat (optional)'},f('emergency_contact','Emergency contact'),f('shift_start','Shift starts','time',{default:'00:00'}),f('shift_end','Shift ends','time',{default:'00:00',help:'Equal start and end means all-day access.'}),f('weekdays','Working days','days',{default:[0,1,2,3,4,5,6]}),status],columns:[['name','Staff member'],['category','Role'],['company','Agency'],['shift_start','Shift from'],['shift_end','Until'],['presence','Presence'],['status','Status']]},
  {id:'leaves',title:'Staff leave',subtitle:'Review absence requests before they affect gate access and duty.',icon:AlarmClock,group:'COMMUNITY',roles:[...managers,'staff'],writers:[...managers,'staff'],fields:[f('person_id','Staff member','select',{lookup:'people',filter:x=>x.kind==='staff',...required}),f('starts_on','First day','date',required),f('ends_on','Last day','date',required),f('reason','Reason','textarea',required)],columns:[['person_name','Staff member'],['starts_on','From'],['ends_on','Through'],['reason','Reason'],['status','Decision']]},
  {id:'movements',title:'Entry & exit log',subtitle:'A permanent record of allowed and denied gate movements.',icon:FileClock,group:'SECURITY',roles:[...security,'resident','staff'],export:true,columns:[['subject_name','Person'],['subject_kind','Type'],['gate_name','Gate'],['direction','Direction'],['decision','Decision'],['reason','Reason'],['created_at','Recorded']]},
  {id:'cameras',title:'Gate cameras',subtitle:'Connect camera workers and review the latest authorised gate snapshots.',icon:Camera,group:'SECURITY',roles:security,writers:managers,editable:true,fields:[f('name','Camera name','text',required),f('gate_id','Assigned gate','select',{lookup:'gates',...required}),f('stream_url','Camera RTSP / HTTP URL or device index','text',required),f('face_enabled','Automatic face recognition','boolean',{default:false}),f('face_direction','Crossing records','select',{options:['in','out'],default:'in'}),f('line_axis','Line axis','select',{options:['x','y'],default:'y',help:'x: vertical line; y: horizontal line.'}),f('line_position','Line position (0.1 to 0.9)','number',{default:0.5,min:0.1,max:0.9,help:'Fraction across image width/height.'}),f('line_positive','Cross toward increasing x/y','boolean',{default:true}),f('external_events','Allow external identity event API','boolean',{default:false,help:'Enable only for your separately trusted identity integration.'}),f('active','Active','boolean',{default:true})],columns:[['name','Camera'],['gate_name','Gate'],['online','Live heartbeat'],['device_configured','Device key'],['active','Enabled']]},
  {id:'incidents',title:'Security & emergencies',subtitle:'Report concerns, acknowledge alerts and document resolutions.',icon:ShieldAlert,group:'SECURITY',roles:[...security,'resident','staff'],writers:[...security,'resident','staff'],fields:[f('title','Incident title','text',required),f('description','What happened?','textarea',required),f('severity','Priority','select',{options:['normal','high','critical'],default:'normal'}),f('gate_id','Gate (optional)','select',{lookup:'gates'}),{...flat,required:false}],columns:[['title','Incident'],['severity','Priority'],['flat_label','Home'],['status','Response'],['created_at','Reported']]},
  {id:'patrols',title:'Guard patrols',subtitle:'Log completed rounds and observations from every checkpoint.',icon:MapPin,group:'SECURITY',roles:security,writers:security,export:true,fields:[f('gate_id','Duty gate','select',{lookup:'gates',...required}),f('checkpoint','Checkpoint','text',required),f('note','Observation','textarea',required)],columns:[['checkpoint','Checkpoint'],['gate_name','Duty gate'],['note','Observation'],['created_at','Recorded']]},
  {id:'deliveries',title:'Parcel desk',subtitle:'Track received parcels and hand them over with a collection code.',icon:Package,group:'DAILY OPERATIONS',roles:[...security,'resident'],writers:security,fields:[flat,f('courier','Courier / sender','text',required),f('reference','Tracking reference'),f('description','Parcel description')],columns:[['courier','Courier'],['flat_label','For'],['reference','Tracking reference'],['description','Package'],['status','Status'],['created_at','Received']]},
  {id:'vehicles',title:'Resident vehicles',subtitle:'Keep vehicles linked to their homes and allocated parking spaces.',icon:Car,group:'DAILY OPERATIONS',roles:[...security,'resident'],writers:[...managers,'resident'],editable:true,fields:[f('plate','Vehicle number','text',required),flat,f('category','Vehicle type','select',{options:['car','bike','other'],default:'car'}),f('model','Make / model'),f('active','Active','boolean',{default:true})],columns:[['plate','Vehicle'],['flat_label','Home'],['category','Type'],['model','Make / model'],['active','Active']]},
  {id:'parking',title:'Parking allocation',subtitle:'Allocate compatible slots without double-booking a vehicle.',icon:Car,group:'DAILY OPERATIONS',roles:[...security,'resident','accountant'],writers:managers,editable:true,fields:[f('code','Slot number','text',required),f('location','Location','text',required),f('category','Slot type','select',{options:['car','bike','other'],default:'car'}),f('vehicle_id','Allocated vehicle','select',{lookup:'vehicles'}),f('status','Status','select',{options:['active','maintenance'],default:'active'})],columns:[['code','Slot'],['location','Location'],['category','Type'],['vehicle_plate','Vehicle'],['status','Availability']]},
  {id:'complaints',title:'Helpdesk & requests',subtitle:'From first report to staff assignment, resolution and resident sign-off.',icon:ClipboardList,group:'DAILY OPERATIONS',roles:all,writers:all.filter(x=>x!=='accountant'),export:true,fields:[f('title','Request title','text',required),f('description','Describe the issue','textarea',required),{...flat,required:false},f('category','Category','select',{options:['plumbing','electrical','cleaning','security','noise','general'],default:'general'}),f('priority','Priority','select',{options:['normal','high','urgent'],default:'normal'})],columns:[['title','Request'],['flat_label','Home'],['category','Category'],['priority','Priority'],['assigned_name','Assigned to'],['status','Progress']]},
  {id:'invoices',title:'Maintenance & dues',subtitle:'Monthly contributions, utility charges and transparent balances.',icon:Wallet,group:'ACCOUNTS',roles:[...finance,'resident'],writers:finance,export:true,fields:[flat,f('period','Billing month','month',required),f('category','Charge type','select',{options:['maintenance','utility','other'],default:'maintenance'}),f('description','Description','text',required),f('amount_paise','Amount (₹)','money',{...required,min:.01}),f('due_on','Due date','date',required)],columns:[['number','Invoice'],['flat_label','Home'],['period','Month'],['amount_paise','Amount'],['balance_paise','Outstanding'],['due_on','Due'],['status','Status']]},
  {id:'payments',title:'Payments & receipts',subtitle:'Record verified offline payments and track refund adjustments.',icon:Receipt,group:'ACCOUNTS',roles:[...finance,'resident'],writers:finance,export:true,fields:[f('invoice_id','Invoice','select',{lookup:'invoices',filter:x=>x.balance_paise>0,...required}),f('amount_paise','Amount received (₹)','money',{...required,min:.01}),f('method','Payment method','select',{options:['cash','upi','bank','cheque'],default:'upi'}),f('reference','Unique transaction / receipt reference','text',required)],columns:[['reference','Reference'],['invoice_number','Invoice'],['amount_paise','Amount'],['method','Method'],['refunded','Refund recorded'],['created_at','Received']]},
  {id:'expenses',title:'Society expenses',subtitle:'Document society spending with references, evidence and approval.',icon:NotebookPen,group:'ACCOUNTS',roles:finance,writers:finance,export:true,fields:[f('title','Expense title','text',required),f('category','Category','select',{options:['utilities','repairs','salary','supplies','other'],default:'repairs'}),f('amount_paise','Amount (₹)','money',{...required,min:.01}),f('vendor_id','Vendor (optional)','select',{lookup:'vendors'}),f('spent_on','Expense date','date',required),f('reference','Voucher / bill reference','text',required)],columns:[['title','Expense'],['category','Category'],['amount_paise','Amount'],['reference','Voucher'],['spent_on','Date'],['status','Approval']]},
  {id:'amenities',title:'Community amenities',subtitle:'Set opening hours, shared capacity and booking charges.',icon:CalendarDays,group:'FACILITIES',roles:all,writers:managers,editable:true,fields:[f('name','Amenity name','text',required),f('location','Location','text',required),f('capacity','People capacity','number',{default:1,min:1,max:1000}),f('open_time','Opens','time',{default:'06:00'}),f('close_time','Closes','time',{default:'22:00'}),f('hourly_fee_paise','Hourly fee (₹)','money'),f('active','Available','boolean',{default:true})],columns:[['name','Amenity'],['location','Location'],['capacity','Capacity'],['open_time','Opens'],['close_time','Closes'],['hourly_fee_paise','Hourly fee'],['active','Available']]},
  {id:'bookings',title:'Amenity reservations',subtitle:'Reserve a space with capacity checks and automatic fee invoicing.',icon:CalendarDays,group:'FACILITIES',roles:[...managers,'resident'],writers:[...managers,'resident'],fields:[f('amenity_id','Amenity','select',{lookup:'amenities',...required}),flat,f('starts_at','Starts at','datetime',required),f('ends_at','Ends at','datetime',required),f('people','People attending','number',{default:1,min:1,max:1000}),f('note','Purpose / note')],columns:[['amenity_name','Amenity'],['flat_label','Home'],['starts_at','Starts'],['ends_at','Ends'],['people','People'],['fee_paise','Fee'],['status','Status']]},
  {id:'assets',title:'Assets & maintenance',subtitle:'Keep lifts, pumps, generators and other shared equipment serviceable.',icon:Wrench,group:'FACILITIES',roles:[...managers,'staff'],writers:managers,editable:true,fields:[f('name','Asset name','text',required),f('category','Type','select',{options:['lift','generator','water_pump','fire_equipment','electrical','other'],default:'lift'}),f('location','Location','text',required),f('vendor_id','Service vendor','select',{lookup:'vendors'}),f('next_service','Next service date','date'),f('status','Condition','select',{options:['active','maintenance','retired'],default:'active'}),f('notes','Service notes','textarea')],columns:[['name','Asset'],['category','Type'],['location','Location'],['next_service','Next service'],['status','Condition']]},
  {id:'vendors',title:'Vendors & contracts',subtitle:'A shared directory for trusted service agencies and contractors.',icon:Store,group:'FACILITIES',roles:finance,writers:managers,editable:true,fields:[f('name','Vendor name','text',required),f('category','Service category','text',required),f('contact','Contact person'),f('phone','Phone','tel'),f('contract_until','Contract ends','date'),f('active','Active','boolean',{default:true})],columns:[['name','Vendor'],['category','Service'],['contact','Contact'],['phone','Phone'],['contract_until','Contract expiry'],['active','Active']]},
  {id:'notices',title:'Notice board',subtitle:'Publish society updates for the whole community or a specific audience.',icon:Megaphone,group:'COMMUNICATION',roles:all,writers:managers,editable:true,fields:[f('title','Notice title','text',required),f('body','Announcement','textarea',required),f('audience','Audience','select',{options:['all','residents','staff'],default:'all'}),f('pinned','Pin to dashboard','boolean',{default:false}),f('expires_on','Show until (optional)','date')],columns:[['title','Announcement'],['audience','Audience'],['pinned','Pinned'],['expires_on','Visible until'],['created_at','Published']]},
  {id:'contacts',title:'Emergency directory',subtitle:'Keep verified society, medical, fire and maintenance contacts accessible.',icon:Contact,group:'COMMUNICATION',roles:all,writers:managers,editable:true,fields:[f('name','Name / service','text',required),f('category','Category','text',required),f('phone','Phone','tel',required),f('available','Availability','text',{default:'24 hours'})],columns:[['name','Service'],['category','Category'],['phone','Call'],['available','Availability']]},
  {id:'gates',title:'Gate setup',subtitle:'Create dedicated entry and exit points or a shared two-way gate.',icon:DoorOpen,group:'ADMINISTRATION',roles:managers,writers:managers,editable:true,fields:[f('name','Gate name','text',required),f('direction','Direction','select',{options:['in','out','both'],default:'both'}),f('active','Active','boolean',{default:true})],columns:[['name','Gate'],['direction','Direction'],['active','Enabled']]},
  {id:'guard-assignments',title:'Guard assignments',subtitle:'Limit each guard to the gates they are responsible for.',icon:KeyRound,group:'ADMINISTRATION',roles:managers,writers:managers,fields:[f('user_id','Guard account','select',{lookup:'users',filter:x=>x.role==='guard',...required}),f('gate_id','Gate','select',{lookup:'gates',...required})],columns:[['user_id','Guard'],['gate_id','Gate'],['created_at','Assigned']]},
  {id:'users',title:'User accounts',subtitle:'Create individual logins with the right role and resident or staff link.',icon:Users,group:'ADMINISTRATION',roles:managers,writers:['admin'],editable:true,fields:[f('name','Display name','text',required),f('username','Username','text',required),f('email','Account email','email',{help:'Account owner verifies this address before access.'}),f('role','Account role','select',{options:all,default:'resident'}),f('person_id','Linked resident / staff','select',{lookup:'people',help:'Required for resident and staff roles; leave empty for management and guards.'}),f('password','Password (12+ characters)','password',{help:'Required for new users. Leave blank to keep an existing password.'}),f('active','Account active','boolean',{default:true})],columns:[['name','Name'],['username','Username'],['role','Role'],['active','Active'],['created_at','Created']]},
  {id:'audit',title:'Audit trail',subtitle:'Review who changed records, approved requests and recorded access.',icon:FileClock,group:'ADMINISTRATION',roles:['admin'],export:true,columns:[['actor_name','Actor'],['action','Action'],['resource','Module'],['created_at','When']]},
  {id:'integrations',title:'Integrations',subtitle:'Payments, messaging and face recognition.',icon:Settings,group:'ADMINISTRATION',roles:['admin']},
  {id:'settings',title:'Society settings',subtitle:'Your community profile, regional settings and account security.',icon:Settings,group:'ADMINISTRATION',roles:all},
];
