import {useEffect,useRef,useState,type ReactNode} from 'react';
import {X,Search,LoaderCircle,ArrowLeft,ArrowRight,Inbox,AlertCircle} from 'lucide-react';
import {api,type Row,label} from './api';

export function useData<T>(path:string,version=0){
  const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;setData(null);setLoading(true);setError('');async function refresh(){try{const next=await api<T>(path);if(active){setData(next);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}}refresh();const id=setInterval(refresh,15000);return()=>{active=false;clearInterval(id);};},[path,version]);
  return {data,error,loading};
}
export function Status({value}:{value:string}){return <span className={'badge badge-'+value}>{label(value)}</span>;}
export function Empty({title='Nothing here yet',children}:{title?:string;children?:ReactNode}){return <div className="empty"><div className="empty-icon"><Inbox size={28}/></div><h3>{title}</h3><p>{children||'New records will appear here as your society gets started.'}</p></div>;}
export function ErrorBox({message}:{message:string}){return message?<div role="alert" className="error-box"><AlertCircle size={18}/>{message}</div>:null;}
export function Loading(){return <div className="loading" role="status"><LoaderCircle className="spin" size={22}/> Loading your community…</div>;}
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const node=dialog.current;node?.showModal();return()=>node?.close();},[]);
  return <dialog ref={dialog} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose();}}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
export function SearchBox({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label className="search"><Search size={18}/><input aria-label="Search records" placeholder="Search records…" value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function Pagination({offset,total,onChange}:{offset:number;total:number;onChange:(v:number)=>void}){return <div className="pagination"><span>{total?`${offset+1}–${Math.min(offset+50,total)} of ${total}`:'0 records'}</span><div><button className="icon-button" disabled={!offset} aria-label="Previous page" onClick={()=>onChange(Math.max(0,offset-50))}><ArrowLeft size={16}/></button><button className="icon-button" disabled={offset+50>=total} aria-label="Next page" onClick={()=>onChange(offset+50)}><ArrowRight size={16}/></button></div></div>;}
export type Field={key:string;label:string;type?:string;required?:boolean;options?:string[];lookup?:string;filter?:(r:Row)=>boolean;default?:any;min?:number;max?:number;help?:string};
export function Form({fields,initial={},options,onSave,onClose,submit='Save record'}:{fields:Field[];initial?:Row;options:Row;onSave:(v:Row)=>Promise<unknown>;onClose:()=>void;submit?:string}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);try{const form=new FormData(e.currentTarget),data:Row={};for(const f of fields){const raw=String(form.get(f.key)??'');data[f.key]=f.type==='number'?Number(raw||0):f.type==='money'?Math.round(Number(raw||0)*100):f.type==='boolean'?raw==='true':f.type==='datetime'?new Date(raw).toISOString():f.type==='days'?form.getAll(f.key).map(Number):raw||((f.lookup||f.type==='date'||f.type==='password'||f.type==='email')?null:'');}await onSave(data);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form onSubmit={save}><div className="form-grid">{fields.map(f=>{let value=initial[f.key]??f.default??'';if(f.type==='money')value=Number(value)/100;if(f.type==='datetime'&&value){const d=new Date(value);value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}if(f.type==='days')return <fieldset className="field full" key={f.key}><legend>{f.label}</legend><div className="days">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day,i)=><label key={day}><input name={f.key} type="checkbox" value={i} defaultChecked={Array.isArray(value)&&value.includes(i)}/>{day}</label>)}</div></fieldset>;return <label className={'field '+(f.type==='textarea'?'full':'')} key={f.key}><span>{f.label}{f.required&&<b> *</b>}</span>{f.type==='textarea'?<textarea name={f.key} required={f.required} defaultValue={value} rows={4} maxLength={10000}/>:f.lookup||f.options||f.type==='boolean'?<select name={f.key} required={f.required} defaultValue={String(value)}>{f.type==='boolean'?<><option value="true">Yes / active</option><option value="false">No / inactive</option></>:<><option value="">Select {f.label.toLowerCase()}</option>{f.lookup?(options[f.lookup]||[]).filter(f.filter||(()=>true)).map((r:Row)=><option value={r.id} key={r.id}>{r.label}</option>):f.options?.map(x=><option key={x} value={x}>{label(x)}</option>)}</>}</select>:<input name={f.key} type={f.type==='money'?'number':f.type==='datetime'?'datetime-local':f.type||'text'} step={f.type==='money'?'.01':f.type==='number'?'any':undefined} min={f.min??(f.type==='money'?0:undefined)} max={f.max} minLength={f.type==='password'?12:undefined} required={f.required} defaultValue={value} autoComplete={f.type==='password'?'new-password':undefined}/>} {f.help&&<small>{f.help}</small>}</label>;})}</div><ErrorBox message={error}/><div className="modal-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':submit}</button></div></form>;
}
